
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lago-storage-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 # This is the storage class name that we created in CICD
  resources:
    requests:
      storage: 30Gi
