apiVersion: apps/v1
kind: Deployment
metadata:
  name: lago-api-clock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service: lago-api-clock
  template:
    metadata:
      labels:
        app.kubernetes.io/network: "lago-default"
        app.kubernetes.io/service: lago-api-clock
    spec:
      containers:
        - args:
            - ./scripts/start.clock.sh
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lago-secret
                  key: DATABASE_URL
            - name: ENCRYPTION_DETERMINISTIC_KEY
              value: ${LAGO_ENCRYPTION_DETERMINISTIC_KEY:-your-encrpytion-deterministic-key}
            - name: ENCRYPTION_KEY_DERIVATION_SALT
              value: ${LAGO_ENCRYPTION_KEY_DERIVATION_SALT:-your-encrpytion-derivation-salt}
            - name: ENCRYPTION_PRIMARY_KEY
              value: ${LAGO_ENCRYPTION_PRIMARY_KEY:-your-encrpytion-primary-key}
            - name: LAGO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: lago-configmap
                  key: LAGO_API_URL
            - name: LAGO_RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: lago-secret
                  key: API_SECRET
            - name: RAILS_ENV
              value: production
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: REDIS_PASSWORD
              value: ${REDIS_PASSWORD}
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: lago-configmap
                  key: LAGO_REDIS_URL
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: lago-secret
                  key: API_SECRET
            - name: SECRET_KEY_BASE
              value: ${SECRET_KEY_BASE:-your-secret-key-base-hex-64}
          image: getlago/api:v0.40.0-beta
          name: lago-api-clock
          resources: {}
      restartPolicy: Always
status: {}
