apiVersion: apps/v1
kind: Deployment
metadata:
  name: lago-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service: lago-pdf
  template:
    metadata:
      labels:
        app.kubernetes.io/network: "lago-default"
        app.kubernetes.io/service: lago-pdf
    spec:
      containers:
        - image: getlago/lago-gotenberg:7
          name: lago-pdf
      restartPolicy: Always
