name: Setup Config & secret for lago
on: 
    workflow_dispatch:

jobs:
  setup_config_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        

      - name: Create secrets file
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" > secret.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> secret.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> secret.env