apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/network: lago-default
        app.kubernetes.io/name: redis
    spec:
      containers:
        - args:
            - --port
            - "6379"
          image: redis:6.2-alpine
          name: lago-redis
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: lago-redis-data
      restartPolicy: Always
      volumes:
        - name: lago-redis-data
          persistentVolumeClaim:
            claimName: lago-redis-data
