apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lago-redis
  name: lago-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: lago-redis
