apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: app-
metadata:
  name: lago-ressources
commonLabels:
  app: lago

resources:
- ./postgres


configMapGenerator:
- name: lago-configmap
  envs:
  - configmap.env


secretGenerator:
- name: lago-secret
  envs:
  - secret.env