name: Setup Config & secret for lago
on: 
    workflow_dispatch:


env:
  AWS_ACCOUNT_ID: 230410870031
  REGION : eu-west-2
  AWS_NAME_CLUSTER: test-cluster-3

jobs:
  setup_config_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.AWS_NAME_CLUSTER }} --region ${{ env.REGION }}

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Create secrets file
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" > Lago-K8S/secret.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> Lago-K8S/secret.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> Lago-K8S/secret.env

      - name: test postgres lago
        run: |
          cd Lago-K8S
          kustomize build . | kubectl apply -f -
