name: Workflow for deployment in K8S
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update Lago Image
      run: |
        export IMAGE_VERSION=${{ vars.IMAGE_VERSION }}
        envsubst < ./k8s/api/deployment.yaml > ./k8s/api/deployment_updated.yaml
        envsubst < ./k8s/api/worker/deployment.yaml > ./k8s/api/worker/deployment_updated.yaml
        envsubst < ./k8s/api/clock/deployment.yaml > ./k8s/api/clock/deployment_updated.yaml
        envsubst < ./k8s/front/deployment.yaml > ./k8s/front/deployment_updated.yaml
        
        mv ./k8s/api/deployment_updated.yaml ./k8s/api/deployment.yaml
        mv ./k8s/api/worker/deployment_updated.yaml ./k8s/api/worker/deployment.yaml
        mv ./k8s/api/clock/deployment_updated.yaml ./k8s/api/clock/deployment.yaml
        mv ./k8s/front/deployment_updated.yaml ./k8s/front/deployment.yaml


    - name: build using custom actions
      uses : ChocTitans/composite-action@composite
      with :
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-cluster-name: ${{ vars.AWS_NAME_CLUSTER }}
       aws-region: ${{ vars.AWS_REGION }}
       vars: ${{ toJson(vars) }}
       secrets: ${{ toJson(secrets) }}
       path: ./k8s