name: Workflow for deployment of a service in K8S
on: 
    workflow_dispatch:

jobs:
  setup_config_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ vars.AWS_NAME_CLUSTER }} --region ${{ vars.AWS_REGION }}

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Create secrets file
        run: |
          cd ./k8s
          IFS=',' read -ra secret_array <<< "$SECRET_NAMES"
          for secret_name in "${secret_array[@]}"; do
            secret_value="${{ secrets[secret_name] }}"
            echo "$secret_name=$secret_value" >> secret.env
          done
          echo "Exported secrets:"
          cat secret.env
          
      - name: Create ConfigMap file
        run: |
          cd ./k8s
          echo "LAGO_API_URL=${{ vars.LAGO_API_URL }}" > configmap.env
          echo "LAGO_FRONT_URL=${{ vars.LAGO_FRONT_URL }}" >> configmap.env
          echo "LAGO_REDIS_URL=${{ vars.LAGO_REDIS_URL }}" >> configmap.env
          echo "LAGO_PDF_URL=${{ vars.LAGO_PDF_URL }}" >> configmap.env


      - name: Kustomize build & apply
        run: |
          cd ./k8s
          kustomize build . | kubectl apply -f -